@baseUrl = http://127.0.0.1:8080

# получение объявлений
GET {{baseUrl}}/adverts
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/adverts
Content-Type: application/json

{
  "title": "Ржавая бензопила",
  "description": "Только самовывоз",
  "owner": "Иван"
}

###

# создание объявления
POST {{baseUrl}}/adverts
Content-Type: application/json

{
  "title": "Холодильник Орск",
  "description": "Дешево",
  "owner": "Иван"
}

###

# проверка ошибок в создании объявления
POST {{baseUrl}}/adverts
Content-Type: application/json

{
  "title": "Холодильник Орск",
  "description": "Только самовывоз"
}

###

# проверка ошибки Invalid JSON
POST {{baseUrl}}/adverts
Content-Type: application/json

###

# получение одного объявления
GET {{baseUrl}}/adverts/1
Content-Type: application/json

###

# изменение объявления
PATCH {{baseUrl}}/adverts/1
Content-Type: application/json

{
  "id": 1,
  "description": "Совсем новая"
}

###

# проверка ошибки в изменении объявления
PATCH {{baseUrl}}/adverts/1
Content-Type: application/json

# {
#   "id": 1
# }

###

# удаление объявления
DELETE {{baseUrl}}/adverts/2
Content-Type: application/json

###